spring.application.name=tasks

#Clever Cloud
#spring.datasource.url=jdbc:mysql://uo88ytwoaims0lyf:CqjOVDZtMRuSCToOkrp7@b3ra7eiakw9vsqn4j1vi-mysql.services.clever-cloud.com:3306/b3ra7eiakw9vsqn4j1vi

#Local DB
#spring.datasource.username=nazwa_uzytkownika
#spring.datasource.password=twoje_haslo

# Clever Cloud DB - top secret


spring.jpa.database=mysql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

#top secret: trello api data removed
spring.datasource.url=jdbc:mysql://b3ra7eiakw9vsqn4j1vi-mysql.services.clever-cloud.com:3306/b3ra7eiakw9vsqn4j1vi
spring.datasource.username=uo88ytwoaims0lyf
spring.datasource.password=CqjOVDZtMRuSCToOkrp7

trello.api.endpoint.prod=https://api.trello.com/1
trello.app.key=1361c5ba2140278f4726455034953592
trello.app.token=ATTA9c1e162f4e1cbddafd68fe4b5fa5c63555889c3c12adf399352c20a806d5f533CE81D375
trello.app.user=marcincodegithub