spring.application.name=tasks

#Clever Cloud
#spring.datasource.url=jdbc:mysql://uo88ytwoaims0lyf:CqjOVDZtMRuSCToOkrp7@b3ra7eiakw9vsqn4j1vi-mysql.services.clever-cloud.com:3306/b3ra7eiakw9vsqn4j1vi

#Local DB
#spring.datasource.username=nazwa_uzytkownika
#spring.datasource.password=twoje_haslo

# Clever Cloud DB - top secret


spring.jpa.database=mysql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

#top secret: trello api data removed
spring.datasource.url=jdbc:mysql://b3ra7eiakw9vsqn4j1vi-mysql.services.clever-cloud.com:3306/b3ra7eiakw9vsqn4j1vi
spring.datasource.username=uo88ytwoaims0lyf
spring.datasource.password=CqjOVDZtMRuSCToOkrp7

trello.api.endpoint.prod=https://api.trello.com/1
trello.app.key=${TRELLO_KEY}
trello.app.token=${TRELLO_TOKEN}
trello.app.user=marcincodegithub

# EMAIL CONFIGURATION
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

admin.mail=marcin.code.github@gmail.com